#!/bin/sh
#
# Usage: org_compile_pdf <file>
# Description: compiles an org file to pdf
#
org_compile_pdf () {
    if [ -f $1 ]; then
        org_file=$1
        echo "Compiling $org_file to pdf"

        emacs -u "$(id -un)" \
            --batch \
            --eval '(load user-init-file)' \
            $org_file \
            -f org-latex-export-to-pdf

    else
        echo "'$1' is not a valid file"
    fi
}