# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# Commands and Apps to be executed at launch

# Low battery notifications (warn 20%, critical 10%, danger 5%)
exec-once = batsignal -w 20 -c 10 -d 5 -p
